/* eslint-disable quote-props */
/* eslint-disable max-len */
/**
 * Translation file for this resource.
 *
 * This file is generated by combining automatic extraction and manual translations:
 * - The "en" (English) section is automatically extracted from source files
 * - Other language sections can be manually translated or pulled from Transifex
 * - When regenerating, existing manual translations are preserved when the English
 *   source text hasn't changed
 *
 * Structure:
 * - interface: translations for name/description (used by GUI formatMessage)
 * - extensions: translations for extension blocks (used by VM formatMessage)
 * - blocks: translations for Blockly blocks (used by Blockly.Msg)
 */

export default {
    'interface': {
        'en': {
            'max6675.name': 'MAX6675 Module',
            'max6675.description': 'K-type thermocouple temperature measurement module based on MAX6675, the measurement range is 0 ~ 1024 ℃'
        },
        'ru': {
            'max6675.name': 'MAX6675 Module',
            'max6675.description': 'K-type thermocouple temperature measurement module based on MAX6675, the measurement range is 0 ~ 1024 ℃'
        },
        'zh-cn': {
            'max6675.name': 'MAX6675 Module',
            'max6675.description': 'K-type thermocouple temperature measurement module based on MAX6675, the measurement range is 0 ~ 1024 ℃'
        },
        'zh-tw': {
            'max6675.name': 'MAX6675 Module',
            'max6675.description': 'K-type thermocouple temperature measurement module based on MAX6675, the measurement range is 0 ~ 1024 ℃'
        }
    },
    'extensions': {
        'en': {},
        'ru': {},
        'zh-cn': {},
        'zh-tw': {}
    },
    'blocks': {
        'en': {
            'MAX6675_CATEGORY': 'MAX6675',
            'MAX6675_INIT': 'init max6675 pin DO %1 CLK %2 CS %3',
            'MAX6675_READTEMPERATURE': 'max6675 read temperature %1'
        },
        'ru': {
            'MAX6675_CATEGORY': 'MAX6675',
            'MAX6675_INIT': 'init max6675 pin DO %1 CLK %2 CS %3',
            'MAX6675_READTEMPERATURE': 'max6675 read temperature %1'
        },
        'zh-cn': {
            'MAX6675_CATEGORY': 'MAX6675',
            'MAX6675_INIT': 'init max6675 pin DO %1 CLK %2 CS %3',
            'MAX6675_READTEMPERATURE': 'max6675 read temperature %1'
        },
        'zh-tw': {
            'MAX6675_CATEGORY': 'MAX6675',
            'MAX6675_INIT': 'init max6675 pin DO %1 CLK %2 CS %3',
            'MAX6675_READTEMPERATURE': 'max6675 read temperature %1'
        }
    }
};
